name: Unified build and test

on: [push, pull_request]

jobs:
  build:
    name: Minotaur unified build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Recursive checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Free space on runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build re2c z3 libhiredis-dev redis

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Build and test
        working-directory: build
        run: |
          cmake -GNinja ..
          ninja check-llvm-unit clang
          ninja check-alive
          ninja check-minotaur
